import { useRef } from 'react'
import { useGLTF } from '@react-three/drei/core'
import { useFrame } from '@react-three/fiber'
import { BufferGeometry, Material, Mesh } from 'three'

export default function App(props) {
  const ref = useRef(null)
  useFrame((state, delta) => (ref.current.rotation.y += delta / 2))
  return (
    <group ref={ref} {...props}>
      <ambientLight intensity={0.75} />
      <pointLight intensity={1} position={[-10, -25, -10]} />
      <spotLight intensity={2.25} angle={0.2} penumbra={1} position={[-25, 20, -15]} />
      <Model url='/models/react-transformed.glb' />
    </group>
  )
}

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: overlaps (https://sketchfab.com/overlaps)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/models/91964c1ce1a34c3985b6257441efa500
title: Space exploration [WLP series #8]
*/
type Node = {
  geometry: BufferGeometry
  material: Material
}
function Model({ url }: { url: string }) {
  const { nodes } = useGLTF(url)
  const planet002 = nodes.planet002 as Mesh
  const planet003 = nodes.planet003 as Mesh
  if (!planet002 || !planet003) return null
  return (
    <group rotation={[-Math.PI / 2, 0, 0]} position={[0, -7, 0]} scale={7}>
      <group rotation={[Math.PI / 13.5, -Math.PI / 5.8, Math.PI / 5.6]}>
        <mesh
          receiveShadow
          castShadow
          geometry={planet002.geometry as BufferGeometry}
          material={planet002.material as Material}
        />
        <mesh
          receiveShadow
          castShadow
          geometry={planet003.geometry as BufferGeometry}
          material={planet003.material as Material}
        />
      </group>
    </group>
  )
}
