import { Suspense, useRef } from 'react'
import { Box, CameraControls, Environment, useGLTF } from '@react-three/drei/core'
import { useFrame } from '@react-three/fiber'
import { BufferGeometry, Material, Mesh } from 'three'

export default function App(props) {
  const ref = useRef(null)
  useFrame((state, delta) => (ref.current.rotation.y += delta / 2))
  return (
    <group ref={ref} {...props}>
      <directionalLight position={[1, 2, 1.5]} intensity={0.5} castShadow />
      <hemisphereLight intensity={1.5} groundColor='red' />
      <Box args={[2, 2, 2]} position={[0, 0, 0]}>
        <meshBasicMaterial color='red' />
      </Box>
      <Suspense>
        <Model url='/models/turtle.glb' />
      </Suspense>
      <CameraControls minDistance={15} maxDistance={30} makeDefault minPolarAngle={0} maxPolarAngle={Math.PI / 2} />
    </group>
  )
}

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: overlaps (https://sketchfab.com/overlaps)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/models/91964c1ce1a34c3985b6257441efa500
title: Space exploration [WLP series #8]
*/
type Node = {
  geometry: BufferGeometry
  material: Material
}
function Model({ url }: { url: string }) {
  console.log('url', url)
  const { nodes } = useGLTF(url)
  const planet002 = nodes.planet002 as Mesh
  const planet003 = nodes.planet003 as Mesh
  if (!planet002 || !planet003) return null
  return (
    <group rotation={[-Math.PI / 2, 0, 0]} position={[0, -7, 0]} scale={7}>
      <group rotation={[Math.PI / 13.5, -Math.PI / 5.8, Math.PI / 5.6]}>
        <mesh
          receiveShadow
          castShadow
          geometry={planet002.geometry as BufferGeometry}
          material={planet002.material as Material}
        />
        <mesh
          receiveShadow
          castShadow
          geometry={planet003.geometry as BufferGeometry}
          material={planet003.material as Material}
        />
      </group>
    </group>
  )
}
